### ISSUE TITLE
Add a 'subset' ability

### ISSUE THREAD

**Issue by vorant** [mmastrac/webfont-dl#7]
I'd like to download a fonts with Cyrilic or Greek symbols

**Comment by mmastrac** [comment]
You can use &subset=cyrillic today in the URL you pass which should download only the range you specify. Note that the tool doesn't specifically generate or parse Google Webfont URLs. I can add an example to demo this if it might help. Let me know if that works for you!

**Comment by mmastrac** [comment]
Closing this for now -- feel free to re-open if the suggestion doesn't work. Thanks!
