### ISSUE TITLE
Omit SVG by default

### ISSUE THREAD

**Issue by mathiasbynens** [mmastrac/webfont-dl#9]
SVG is not needed anymore nowadays.

**Comment by mmastrac** [comment]
This is a good thought. The only reason to support SVG fonts right now is if you have a specific reason for supporting old android browsers (pre 4.4) or really really old iOS (<= 5).

Adding 'help wanted' in case someone wants to create a patch. I'll work on this with some of the other bugs.

**Comment by mmastrac** [comment]
Supporting references that illustrate almost complete woff coverage. In fact, woff + eot is pretty much 100% of today's global browsers (other than Opera Mini that doesn't support any font extensibility as far as I can tell): 

http://caniuse.com/#search=woff

http://caniuse.com/#feat=svg-fonts

http://caniuse.com/#search=eot

I'd suggest that we change the default to inline WOFF and link EOT, with the rest omitted.

**Comment by mmastrac** [comment]
Digging into this more, if we keep TTF linked that covers the "ancient android" and gives you iOS support all the way back to 4.3. Not too shabby.

So: WOFF: inline, EOT: link, TTF: link

**Comment by mmastrac** [comment]
Updated
